### ISSUE TITLE
TypeError: '>' not supported between instances of 'dict_values' and 'int‘

### ISSUE THREAD

**Issue by bibibabibo26** [Fangyh09/PoseDatasets#3]
python mpii_dataset.py have error as：
mpii_dataset.py:79: FutureWarning: elementwise != comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  if annopoint != []:
mpii_dataset.py:102: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  for v in annopoint['is_visible'][0]]
Traceback (most recent call last):
  File "mpii_dataset.py", line 192, in <module>
    save_joints()
  File "mpii_dataset.py", line 122, in save_joints
    if not ok(feed_dict):
  File "/content/drive/MyDrive/HumanPoseDemo/clone/PoseDatasets/img_filter.py", line 56, in ok
    keypoint_num = np.sum(vis > 0)
TypeError: '>' not supported between instances of 'dict_values' and 'int'
How to solve？please！

**Comment by jzsherlock4869** [comment]
you can change the line 50-51 to the following

```
    if vis is not None and type(vis) is dict:
        vis = np.array(list(vis.values()))
```
